import { chromium } from '@playwright/test';
const WS='f17c0fb5-7ca6-4760-94d1-e673dd447cce';
const SP=process.env.SP;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport:{width:1280,height:1000} });
page.on('console',(m)=>{ if(m.type()==='error') console.log('[console]',m.text().slice(0,200)); });
await page.goto('http://localhost:3000/en/login');
await page.fill('#email','tutor@email.com'); await page.fill('#password','!Password1234');
await page.click('button[type=submit]');
await page.waitForURL((u)=>!u.pathname.endsWith('/login'),{timeout:60000});
await page.goto(`http://localhost:3000/en/w/${WS}/students`, { waitUntil:'domcontentloaded', timeout:120000 });
await page.waitForTimeout(6000);
await page.getByRole('link', { name: /phase2-check/ }).first().click();
await page.waitForURL(/students\//, { timeout: 60000 });
await page.waitForTimeout(9000);
await page.screenshot({ path:`${SP}/96-card.png`, fullPage:true });
const text = await page.locator('main').last().innerText();
console.log('--- card text (head) ---');
console.log(text.slice(0, 260));
console.log('has schedule button:', await page.getByRole('button', { name: 'Schedule lessons' }).count());
await browser.close();
